variables:
  isReleaseMode: ${{ startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}

trigger:
  branches:
    include:
      - master
  tags:
    include:
      - '*'

pr:
  - master

jobs:
- job: 'Build_Windows'
  pool:
    vmImage: 'windows-2019'
  variables:
    build_config: RelWithDebInfo
    DepsBasePath: 'D:\obsdependencies'
    DepsPath32: '$(DepsBasePath)\win32'
    DepsPath64: '$(DepsBasePath)\win64'
    QtBaseDir: 'D:\QtDep'
    QTDIR32: '$(QtBaseDir)\5.15.2\msvc2019'
    QTDIR64: '$(QtBaseDir)\5.15.2\msvc2019_64'
    OBSPath: 'D:\obs-studio'
    OBSTargetVersion: '26.1.0'
  steps:
    - checkout: self
      submodules: true

    - script: ./CI/install-qt-win.cmd
      displayName: 'Install Qt'
      env:
        QtBaseDir: $(QtBaseDir)

    - task: Cache@2
      displayName: Restore cached OBS Studio dependencies
      inputs:
        key: 'obsdeps | "$(Agent.OS)"'
        restoreKeys: |
          obsdeps | "$(Agent.OS)"
        path: $(DepsBasePath)

    - script: ./CI/download-obs-deps.cmd
      displayName: 'Download OBS Studio dependencies'

    - task: Cache@2
      displayName: Restore cached OBS Studio builds
      inputs:
        key: 'obs | "$(Agent.OS)"'
        restoreKeys: |
          obs | "$(Agent.OS)"
        path: $(OBSPath)

    - script: ./CI/checkout-cmake-obs-windows.cmd
      displayName: 'Checkout & CMake OBS Studio'
      env:
        build_config: $(build_config)
        DepsPath32: $(DepsPath32)
        DepsPath64: $(DepsPath64)
        QTDIR32: $(QTDIR32)
        QTDIR64: $(QTDIR64)
        OBSPath: $(OBSPath)

    - task: MSBuild@1
      displayName: 'Build OBS Studio 64-bit'
      inputs:
        msbuildArguments: '/m /p:Configuration=$(build_config)'
        solution: '$(OBSPath)\build64\obs-studio.sln'

    - script: ./CI/prepare-windows.cmd
      displayName: 'CMake obs-auto-subtitle'
      env:
        build_config: $(build_config)
        QTDIR32: $(QTDIR32)
        QTDIR64: $(QTDIR64)
        OBSPath: $(OBSPath)

    - task: MSBuild@1
      displayName: 'Build obs-auto-subtitle 64-bit'
      inputs:
        msbuildArguments: '/m /p:Configuration=$(build_config)'
        solution: '.\build64\obs-auto-subtitle.sln'

    - script: ./CI/package-windows.cmd
      displayName: 'Package obs-auto-subtitle'

    - task: PublishBuildArtifacts@1
      displayName: 'Upload package artifacts'
      inputs:
        pathtoPublish: './package'
        artifactName: 'windows_build'

- job: 'Build_macOS'
  pool:
    vmImage: 'macos-10.15'
  variables:
    OBSTargetVersion: '26.1.0'
  steps:
    - checkout: self
      submodules: true

    - script: ./CI/install-dependencies-macos.sh
      displayName: 'Install dependencies'

    - script: ./CI/install-build-obs-macos.sh
      displayName: 'Build OBS'
      env:
        OBSTargetVersion: $(OBSTargetVersion)

    - script: ./CI/build-macos.sh
      displayName: 'Build obs-auto-subtitle'

#    - task: InstallAppleCertificate@1
#      displayName: 'Install release signing certificates'
#      condition: eq(variables['isReleaseMode'], true)
#      inputs:
#        certSecureFile: 'Certificates.p12'
#        certPwd: $(secrets.macOS.certificatesImportPassword)

    - script: ./CI/package-macos.sh
      displayName: 'Package obs-auto-subtitle'
      env:
        RELEASE_MODE: $(isReleaseMode)
        CODE_SIGNING_IDENTITY: $(secrets.macOS.codeSigningIdentity)
        INSTALLER_SIGNING_IDENTITY: $(secrets.macOS.installerSigningIdentity)
        AC_USERNAME: $(secrets.macOS.notarization.username)
        AC_PASSWORD: $(secrets.macOS.notarization.password)
        AC_PROVIDER_SHORTNAME: $(secrets.macOS.notarization.providerShortName)

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: './release'
        artifactName: 'macos_build'
